application: g-srv01
version: 1
runtime: python
api_version: 1

handlers:
- url: /scripts
  static_dir: scripts
- url: /images
  static_dir: images
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico
- url: .*
  script: main.py

builtins:
- datastore_admin: on
